export interface ComponentDef {
  type: string
  description: string
  category: 'layout' | 'input' | 'display' | 'action' | 'chart'
  events?: Record<string, {
    description: string
    mapsTo: string            // Reaction when.event 值
    payload: string           // 传给 handleEvent 的 payload 说明
  }>
  props: Record<string, {
    type: string
    required?: boolean
    description: string
    defaultValue?: unknown
    enum?: string[]
    tier?: 'core' | 'common' | 'styling'
  }>
}

export const componentCatalog: Record<string, ComponentDef> = {
  Row: {
    type: 'Row',
    description: '水平弹性布局容器',
    category: 'layout',
    props: {
      children: { type: 'string[]', required: true, description: '子组件 ID 列表', tier: 'core' },
      gap: { type: 'number', defaultValue: 8, description: '间距(px)', tier: 'styling' },
    },
  },
  Card: {
    type: 'Card',
    description: '卡片容器，带标题和阴影',
    category: 'layout',
    props: {
      children: { type: 'string[]', required: true, description: '子组件 ID 列表', tier: 'core' },
      title: { type: 'string', description: '卡片标题', tier: 'common' },
      width: { type: 'string', defaultValue: '', description: '卡片宽度，如 400px / 100% / 20rem，留空则自适应', tier: 'styling' },
      _w: { type: 'number', description: '在 Dashboard 中占列数，默认占满整行', tier: 'styling' },
    },
  },
  Dashboard: {
    type: 'Dashboard',
    description: 'BI看板 CSS Grid 网格布局容器，子组件通过 _w prop 控制占列数',
    category: 'layout',
    props: {
      children: { type: 'string[]', required: true, description: '子组件 ID 列表', tier: 'core' },
      columns: { type: 'number', defaultValue: 12, description: '栅格列数', tier: 'styling' },
      gap: { type: 'number', defaultValue: 16, description: '卡片间距(px)', tier: 'styling' },
    },
  },
  TextField: {
    type: 'TextField',
    description: '文本输入框，支持 text/number 类型',
    category: 'input',
    events: {
      change: {
        description: '输入值变化时触发',
        mapsTo: 'change',
        payload: '{ field: 组件 props.value 路径, value: 新输入值 }',
      },
      blur: {
        description: '失去焦点时触发',
        mapsTo: 'blur',
        payload: '{ field: 组件 props.value 路径, value: 当前输入值 }',
      },
    },
    props: {
      label: { type: 'string', required: true, description: '标签', tier: 'core' },
      value: { type: 'DynamicString', required: true, description: '绑定的值，支持 DataBinding { path } 或静态字符串', tier: 'core' },
      placeholder: { type: 'string', description: '占位提示文字', tier: 'common' },
      type: {
        type: 'string', defaultValue: 'text', enum: ['text', 'number'],
        description: '输入类型', tier: 'common',
      },
      size: { type: 'string', defaultValue: 'default', enum: ['sm', 'default', 'lg'], description: '输入框尺寸', tier: 'styling' },
      width: { type: 'string', defaultValue: '', description: '宽度 CSS 值，如 200px / 100% / 20rem', tier: 'styling' },
    },
  },
  Select: {
    type: 'Select',
    description: '下拉选择器，选项从数据模型读取',
    category: 'input',
    events: {
      change: {
        description: '选中项变化时触发',
        mapsTo: 'change',
        payload: '{ field: 组件 props.value 路径, value: 选中的值 }',
      },
    },
    props: {
      label: { type: 'string', required: true, description: '标签', tier: 'core' },
      value: { type: 'DynamicString', required: true, description: '绑定的值，支持 DataBinding { path } 或静态值', tier: 'core' },
      options: { type: 'DynamicValue', description: '选项列表，支持 DataBinding { path } 或静态数组 [{ label, value }]', tier: 'core' },
      placeholder: { type: 'string', description: '占位提示', tier: 'common' },
      size: { type: 'string', defaultValue: 'default', enum: ['sm', 'default', 'lg'], description: '选择器尺寸', tier: 'styling' },
      width: { type: 'string', defaultValue: '', description: '宽度 CSS 值，如 200px / 100% / 20rem', tier: 'styling' },
    },
  },
  Text: {
    type: 'Text',
    description: '文本展示，支持 ${/xxx} 模板插值（ExpressionParser）',
    category: 'display',
    props: {
      text: { type: 'DynamicString', required: true, description: '展示文本，支持 ${/xxx} 模板插值引用数据', tier: 'core' },
      size: { type: 'string', defaultValue: 'sm', enum: ['xs', 'sm', 'base', 'lg', 'xl', '2xl'], description: '字号', tier: 'styling' },
      color: { type: 'string', defaultValue: '', description: '文字颜色，Tailwind class (如 text-red-500) 或 hex (如 #ff0000)', tier: 'styling' },
      bold: { type: 'boolean', defaultValue: false, description: '是否加粗', tier: 'styling' },
      italic: { type: 'boolean', defaultValue: false, description: '是否斜体', tier: 'styling' },
    },
  },
  Button: {
    type: 'Button',
    description: '按钮，通过 reactionId 绑定点击事件',
    category: 'action',
    events: {
      click: {
        description: '点击按钮时触发',
        mapsTo: 'click',
        payload: '{ reactionId: 绑定的 Reaction ID }',
      },
    },
    props: {
      label: { type: 'string', required: true, description: '按钮文字', tier: 'core' },
      variant: {
        type: 'string', defaultValue: 'primary', enum: ['primary', 'secondary', 'danger'],
        description: '按钮样式变体', tier: 'styling',
      },
      reactionId: { type: 'string', description: '点击时触发的 Reaction ID', tier: 'common' },
      disabled: { type: 'boolean', defaultValue: false, description: '是否禁用', tier: 'common' },
    },
  },
  DataTable: {
    type: 'DataTable',
    description: '数据表格，支持列定义、动态行数据和可编辑单元格',
    category: 'display',
    props: {
      columns: { type: 'array', required: true, description: '列定义数组 [{ key, label, cellType?, cellProps? }]。cellType 可选: text(默认)/input/number/select', tier: 'core' },
      value: { type: 'DynamicValue', required: true, description: '行数据数组的 DataBinding 路径，如 { "path": "/orders" }', tier: 'core' },
      emptyText: { type: 'string', defaultValue: '暂无数据', description: '无数据时展示的提示文字', tier: 'common' },
      _w: { type: 'number', description: '在 Dashboard 中占列数，默认占满整行', tier: 'styling' },
    },
  },
  Dialog: {
    type: 'Dialog',
    description: '弹窗容器，内部渲染独立 A2UI 子 Surface（独立 DataModel + Reactions），支持多实例隔离',
    category: 'layout',
    props: {
      open: { type: 'DynamicBoolean', required: true, description: '控制弹窗显隐的 DataBinding { path }，值为 true 时打开', tier: 'core' },
      title: { type: 'string', description: '弹窗标题', tier: 'common' },
      source: { type: 'string', required: true, description: '子页面来源：本地 children key（如 "confirmDialog"）或远程 URL', tier: 'core' },
      width: { type: 'string', defaultValue: 'max-w-lg', description: '弹窗宽度 CSS class（如 max-w-lg / max-w-2xl / max-w-4xl）', tier: 'styling' },
    },
  },
  BarChart: {
    type: 'BarChart',
    description: '柱状图，支持动态数据绑定，适合分类对比场景',
    category: 'chart',
    events: {
      chartClick: {
        description: '点击柱子时触发',
        mapsTo: 'click',
        payload: '{ reactionId: 绑定的 Reaction ID, clickData: 被点击柱子的数据 }',
      },
    },
    props: {
      data: { type: 'DynamicValue', required: true, description: '图表数据数组的 DataBinding { path }', tier: 'core' },
      xField: { type: 'string', required: true, description: 'X 轴分类字段名', tier: 'core' },
      yField: { type: 'string', required: true, description: 'Y 轴数值字段名', tier: 'core' },
      title: { type: 'string', description: '图表标题', tier: 'common' },
      height: { type: 'number', defaultValue: 300, description: '图表高度(px)', tier: 'styling' },
      width: { type: 'string', defaultValue: '100%', description: '图表宽度，如 100% / 500px / 20rem', tier: 'styling' },
      color: { type: 'string', defaultValue: '#1890ff', description: '柱状图填充颜色', tier: 'styling' },
      showLegend: { type: 'boolean', defaultValue: true, description: '是否显示图例', tier: 'common' },
      showTooltip: { type: 'boolean', defaultValue: true, description: '是否显示悬浮提示', tier: 'common' },
      showDataLabel: { type: 'boolean', defaultValue: false, description: '是否在图表元素上显示数值标签', tier: 'styling' },
      _w: { type: 'number', description: '在 Dashboard 中占列数，默认占满整行', tier: 'styling' },
      fontSize: { type: 'number', defaultValue: 13, description: '全局字号(px)，影响轴刻度/图例/Tooltip/标签', tier: 'styling' },
      fontFamily: { type: 'string', defaultValue: "Inter, system-ui, -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif", description: '字体栈，保证中英文美观渲染', tier: 'styling' },
      chartMargin: { type: 'number', defaultValue: 16, description: '图表四周边距(px)，文字溢出时加大此值', tier: 'styling' },
      xTickAngle: { type: 'number', defaultValue: 0, description: 'X 轴标签旋转角度(deg)，长文本建议 30~45', tier: 'styling' },
      showGrid: { type: 'boolean', defaultValue: true, description: '是否显示网格线', tier: 'styling' },
      layout: { type: 'string', defaultValue: 'horizontal', enum: ['horizontal', 'vertical'], description: '柱状方向：horizontal 垂直柱 / vertical 水平条形', tier: 'styling' },
      barSize: { type: 'number', description: '固定柱宽(px)，不设则自适应', tier: 'styling' },
      referenceValue: { type: 'number', description: '参考线数值，标注 KPI 目标线', tier: 'common' },
      referenceLabel: { type: 'string', description: '参考线标签文字', tier: 'common' },
      referenceColor: { type: 'string', defaultValue: '#ff4d4f', description: '参考线颜色', tier: 'styling' },
      targetValue: { type: 'number', description: '条件着色阈值，高于此值达标绿、低于未达标红', tier: 'common' },
      colorAbove: { type: 'string', defaultValue: '#52c41a', description: '达标（高于阈值）的颜色', tier: 'styling' },
      colorBelow: { type: 'string', defaultValue: '#ff4d4f', description: '未达标（低于阈值）的颜色', tier: 'styling' },
      reactionId: { type: 'string', description: '点击图表元素时触发的 Reaction ID', tier: 'common' },
    },
  },
  LineChart: {
    type: 'LineChart',
    description: '折线图，支持动态数据绑定，适合趋势展示',
    category: 'chart',
    events: {
      chartClick: {
        description: '点击数据点时触发',
        mapsTo: 'click',
        payload: '{ reactionId: 绑定的 Reaction ID, clickData: 被点击点的数据 }',
      },
    },
    props: {
      data: { type: 'DynamicValue', required: true, description: '图表数据数组的 DataBinding { path }', tier: 'core' },
      xField: { type: 'string', required: true, description: 'X 轴字段名', tier: 'core' },
      yField: { type: 'string', required: true, description: 'Y 轴字段名', tier: 'core' },
      title: { type: 'string', description: '图表标题', tier: 'common' },
      height: { type: 'number', defaultValue: 300, description: '图表高度(px)', tier: 'styling' },
      width: { type: 'string', defaultValue: '100%', description: '图表宽度，如 100% / 500px / 20rem', tier: 'styling' },
      color: { type: 'string', defaultValue: '#1890ff', description: '折线颜色', tier: 'styling' },
      showLegend: { type: 'boolean', defaultValue: true, description: '是否显示图例', tier: 'common' },
      showTooltip: { type: 'boolean', defaultValue: true, description: '是否显示悬浮提示', tier: 'common' },
      showDataLabel: { type: 'boolean', defaultValue: false, description: '是否在图表元素上显示数值标签', tier: 'styling' },
      _w: { type: 'number', description: '在 Dashboard 中占列数，默认占满整行', tier: 'styling' },
      fontSize: { type: 'number', defaultValue: 13, description: '全局字号(px)，影响轴刻度/图例/Tooltip/标签', tier: 'styling' },
      fontFamily: { type: 'string', defaultValue: "Inter, system-ui, -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif", description: '字体栈，保证中英文美观渲染', tier: 'styling' },
      chartMargin: { type: 'number', defaultValue: 16, description: '图表四周边距(px)，文字溢出时加大此值', tier: 'styling' },
      xTickAngle: { type: 'number', defaultValue: 0, description: 'X 轴标签旋转角度(deg)，长文本建议 30~45', tier: 'styling' },
      showGrid: { type: 'boolean', defaultValue: true, description: '是否显示网格线', tier: 'styling' },
      showDot: { type: 'boolean', defaultValue: true, description: '是否显示数据点圆点', tier: 'styling' },
      strokeWidth: { type: 'number', defaultValue: 2, description: '折线粗细(px)', tier: 'styling' },
      curveType: { type: 'string', defaultValue: 'monotone', enum: ['monotone', 'linear', 'step'], description: '曲线类型：smooth / linear / step', tier: 'styling' },
      referenceValue: { type: 'number', description: '参考线数值，标注 KPI 目标线', tier: 'common' },
      referenceLabel: { type: 'string', description: '参考线标签文字', tier: 'common' },
      referenceColor: { type: 'string', defaultValue: '#ff4d4f', description: '参考线颜色', tier: 'styling' },
      targetValue: { type: 'number', description: '条件着色阈值，高于此值达标绿、低于未达标红', tier: 'common' },
      colorAbove: { type: 'string', defaultValue: '#52c41a', description: '达标（高于阈值）的颜色', tier: 'styling' },
      colorBelow: { type: 'string', defaultValue: '#ff4d4f', description: '未达标（低于阈值）的颜色', tier: 'styling' },
      reactionId: { type: 'string', description: '点击图表元素时触发的 Reaction ID', tier: 'common' },
    },
  },
  PieChart: {
    type: 'PieChart',
    description: '饼图，支持动态数据绑定，适合占比展示',
    category: 'chart',
    events: {
      chartClick: {
        description: '点击扇区时触发',
        mapsTo: 'click',
        payload: '{ reactionId: 绑定的 Reaction ID, clickData: 被点击扇区的数据 }',
      },
    },
    props: {
      data: { type: 'DynamicValue', required: true, description: '图表数据数组的 DataBinding { path }', tier: 'core' },
      labelField: { type: 'string', required: true, description: '扇区名称字段名', tier: 'core' },
      valueField: { type: 'string', required: true, description: '扇区数值字段名', tier: 'core' },
      title: { type: 'string', description: '图表标题', tier: 'common' },
      height: { type: 'number', defaultValue: 300, description: '图表高度(px)', tier: 'styling' },
      width: { type: 'string', defaultValue: '100%', description: '图表宽度，如 100% / 500px / 20rem', tier: 'styling' },
      colors: { type: 'string', defaultValue: '#1890ff,#52c41a,#faad14,#f5222d,#722ed1', description: '逗号分隔的颜色列表', tier: 'styling' },
      showLegend: { type: 'boolean', defaultValue: true, description: '是否显示图例', tier: 'common' },
      showTooltip: { type: 'boolean', defaultValue: true, description: '是否显示悬浮提示', tier: 'common' },
      showDataLabel: { type: 'boolean', defaultValue: false, description: '是否在图表元素上显示数值标签', tier: 'styling' },
      _w: { type: 'number', description: '在 Dashboard 中占列数，默认占满整行', tier: 'styling' },
      fontSize: { type: 'number', defaultValue: 13, description: '全局字号(px)，影响轴刻度/图例/Tooltip/标签', tier: 'styling' },
      fontFamily: { type: 'string', defaultValue: "Inter, system-ui, -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif", description: '字体栈，保证中英文美观渲染', tier: 'styling' },
      chartMargin: { type: 'number', defaultValue: 16, description: '图表四周边距(px)，文字溢出时加大此值', tier: 'styling' },
      showLabel: { type: 'boolean', defaultValue: true, description: '是否在扇区上显示名称标签', tier: 'styling' },
      innerRadius: { type: 'number', defaultValue: 0, description: '内径(px)，>0 变为环形图，如 60', tier: 'styling' },
      outerRadius: { type: 'number', defaultValue: 80, description: '外径(px)，控制饼图大小', tier: 'styling' },
      labelFormat: { type: 'string', defaultValue: 'name', enum: ['name', 'value', 'percent', 'nameValue', 'namePercent'], description: '标签格式：name 名称 / value 数值 / percent 百分比 / nameValue 名称+数值 / namePercent 名称+百分比', tier: 'styling' },
      labelPosition: { type: 'string', defaultValue: 'outside', enum: ['outside', 'inside'], description: '标签显示位置：outside 外部+引导线（避免裁剪）/ inside 内部', tier: 'styling' },
      labelOffset: { type: 'number', defaultValue: 10, description: '标签与饼图边缘的距离(px)，仅 outside 模式生效', tier: 'styling' },
      targetValue: { type: 'number', description: '条件着色阈值，高于此值达标绿、低于未达标红', tier: 'common' },
      colorAbove: { type: 'string', defaultValue: '#52c41a', description: '达标（高于阈值）的颜色', tier: 'styling' },
      colorBelow: { type: 'string', defaultValue: '#ff4d4f', description: '未达标（低于阈值）的颜色', tier: 'styling' },
      reactionId: { type: 'string', description: '点击图表元素时触发的 Reaction ID', tier: 'common' },
    },
  },
  AreaChart: {
    type: 'AreaChart',
    description: '面积图，支持动态数据绑定，适合体量趋势展示',
    category: 'chart',
    events: {
      chartClick: {
        description: '点击面积图数据点时触发',
        mapsTo: 'click',
        payload: '{ reactionId: 绑定的 Reaction ID, clickData: 被点击数据点的数据 }',
      },
    },
    props: {
      data: { type: 'DynamicValue', required: true, description: '图表数据数组的 DataBinding { path }', tier: 'core' },
      xField: { type: 'string', required: true, description: 'X 轴字段名', tier: 'core' },
      yField: { type: 'string', required: true, description: 'Y 轴字段名', tier: 'core' },
      title: { type: 'string', description: '图表标题', tier: 'common' },
      height: { type: 'number', defaultValue: 300, description: '图表高度(px)', tier: 'styling' },
      width: { type: 'string', defaultValue: '100%', description: '图表宽度，如 100% / 500px / 20rem', tier: 'styling' },
      color: { type: 'string', defaultValue: '#1890ff', description: '面积填充颜色', tier: 'styling' },
      showLegend: { type: 'boolean', defaultValue: true, description: '是否显示图例', tier: 'common' },
      showTooltip: { type: 'boolean', defaultValue: true, description: '是否显示悬浮提示', tier: 'common' },
      showDataLabel: { type: 'boolean', defaultValue: false, description: '是否在图表元素上显示数值标签', tier: 'styling' },
      _w: { type: 'number', description: '在 Dashboard 中占列数，默认占满整行', tier: 'styling' },
      fontSize: { type: 'number', defaultValue: 13, description: '全局字号(px)，影响轴刻度/图例/Tooltip/标签', tier: 'styling' },
      fontFamily: { type: 'string', defaultValue: "Inter, system-ui, -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif", description: '字体栈，保证中英文美观渲染', tier: 'styling' },
      chartMargin: { type: 'number', defaultValue: 16, description: '图表四周边距(px)，文字溢出时加大此值', tier: 'styling' },
      xTickAngle: { type: 'number', defaultValue: 0, description: 'X 轴标签旋转角度(deg)，长文本建议 30~45', tier: 'styling' },
      showGrid: { type: 'boolean', defaultValue: true, description: '是否显示网格线', tier: 'styling' },
      strokeWidth: { type: 'number', defaultValue: 2, description: '边线粗细(px)', tier: 'styling' },
      fillOpacity: { type: 'number', defaultValue: 0.3, description: '填充透明度(0~1)', tier: 'styling' },
      curveType: { type: 'string', defaultValue: 'monotone', enum: ['monotone', 'linear', 'step'], description: '曲线类型', tier: 'styling' },
      referenceValue: { type: 'number', description: '参考线数值，标注 KPI 目标线', tier: 'common' },
      referenceLabel: { type: 'string', description: '参考线标签文字', tier: 'common' },
      referenceColor: { type: 'string', defaultValue: '#ff4d4f', description: '参考线颜色', tier: 'styling' },
      targetValue: { type: 'number', description: '条件着色阈值，高于此值达标绿、低于未达标红', tier: 'common' },
      colorAbove: { type: 'string', defaultValue: '#52c41a', description: '达标（高于阈值）的颜色', tier: 'styling' },
      colorBelow: { type: 'string', defaultValue: '#ff4d4f', description: '未达标（低于阈值）的颜色', tier: 'styling' },
      reactionId: { type: 'string', description: '点击图表元素时触发的 Reaction ID', tier: 'common' },
    },
  },
  ComposedChart: {
    type: 'ComposedChart',
    description: '组合图，同一坐标系混合柱状+折线，适合双指标对比',
    category: 'chart',
    events: {
      chartClick: {
        description: '点击柱状或折线元素时触发',
        mapsTo: 'click',
        payload: '{ reactionId: 绑定的 Reaction ID, clickData: 被点击元素的数据 }',
      },
    },
    props: {
      data: { type: 'DynamicValue', required: true, description: '图表数据数组的 DataBinding { path }', tier: 'core' },
      xField: { type: 'string', required: true, description: 'X 轴字段名', tier: 'core' },
      yField: { type: 'string', required: true, description: 'Y 轴字段名（柱状）', tier: 'core' },
      yField2: { type: 'string', description: '第二 Y 轴字段名（折线）', tier: 'common' },
      title: { type: 'string', description: '图表标题', tier: 'common' },
      height: { type: 'number', defaultValue: 300, description: '图表高度(px)', tier: 'styling' },
      width: { type: 'string', defaultValue: '100%', description: '图表宽度，如 100% / 500px / 20rem', tier: 'styling' },
      color: { type: 'string', defaultValue: '#1890ff', description: '柱状填充颜色', tier: 'styling' },
      color2: { type: 'string', defaultValue: '#52c41a', description: '折线颜色', tier: 'styling' },
      showLegend: { type: 'boolean', defaultValue: true, description: '是否显示图例', tier: 'common' },
      showTooltip: { type: 'boolean', defaultValue: true, description: '是否显示悬浮提示', tier: 'common' },
      showDataLabel: { type: 'boolean', defaultValue: false, description: '是否在图表元素上显示数值标签', tier: 'styling' },
      _w: { type: 'number', description: '在 Dashboard 中占列数，默认占满整行', tier: 'styling' },
      fontSize: { type: 'number', defaultValue: 13, description: '全局字号(px)，影响轴刻度/图例/Tooltip/标签', tier: 'styling' },
      fontFamily: { type: 'string', defaultValue: "Inter, system-ui, -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif", description: '字体栈，保证中英文美观渲染', tier: 'styling' },
      chartMargin: { type: 'number', defaultValue: 16, description: '图表四周边距(px)，文字溢出时加大此值', tier: 'styling' },
      xTickAngle: { type: 'number', defaultValue: 0, description: 'X 轴标签旋转角度(deg)，长文本建议 30~45', tier: 'styling' },
      showGrid: { type: 'boolean', defaultValue: true, description: '是否显示网格线', tier: 'styling' },
      referenceValue: { type: 'number', description: '参考线数值，标注 KPI 目标线', tier: 'common' },
      referenceLabel: { type: 'string', description: '参考线标签文字', tier: 'common' },
      referenceColor: { type: 'string', defaultValue: '#ff4d4f', description: '参考线颜色', tier: 'styling' },
      targetValue: { type: 'number', description: '条件着色阈值，高于此值达标绿、低于未达标红', tier: 'common' },
      colorAbove: { type: 'string', defaultValue: '#52c41a', description: '达标（高于阈值）的颜色', tier: 'styling' },
      colorBelow: { type: 'string', defaultValue: '#ff4d4f', description: '未达标（低于阈值）的颜色', tier: 'styling' },
      reactionId: { type: 'string', description: '点击图表元素时触发的 Reaction ID', tier: 'common' },
    },
  },
  ScatterChart: {
    type: 'ScatterChart',
    description: '散点图，适合二维数据分布和相关性分析',
    category: 'chart',
    events: {
      chartClick: {
        description: '点击散点时触发',
        mapsTo: 'click',
        payload: '{ reactionId: 绑定的 Reaction ID, clickData: 被点击散点的数据 }',
      },
    },
    props: {
      data: { type: 'DynamicValue', required: true, description: '图表数据数组的 DataBinding { path }', tier: 'core' },
      xField: { type: 'string', required: true, description: 'X 轴字段名', tier: 'core' },
      yField: { type: 'string', required: true, description: 'Y 轴字段名', tier: 'core' },
      title: { type: 'string', description: '图表标题', tier: 'common' },
      height: { type: 'number', defaultValue: 300, description: '图表高度(px)', tier: 'styling' },
      width: { type: 'string', defaultValue: '100%', description: '图表宽度，如 100% / 500px / 20rem', tier: 'styling' },
      color: { type: 'string', defaultValue: '#1890ff', description: '散点颜色', tier: 'styling' },
      showLegend: { type: 'boolean', defaultValue: true, description: '是否显示图例', tier: 'common' },
      showTooltip: { type: 'boolean', defaultValue: true, description: '是否显示悬浮提示', tier: 'common' },
      showDataLabel: { type: 'boolean', defaultValue: false, description: '是否在图表元素上显示数值标签', tier: 'styling' },
      _w: { type: 'number', description: '在 Dashboard 中占列数，默认占满整行', tier: 'styling' },
      fontSize: { type: 'number', defaultValue: 13, description: '全局字号(px)，影响轴刻度/图例/Tooltip/标签', tier: 'styling' },
      fontFamily: { type: 'string', defaultValue: "Inter, system-ui, -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif", description: '字体栈，保证中英文美观渲染', tier: 'styling' },
      chartMargin: { type: 'number', defaultValue: 16, description: '图表四周边距(px)，文字溢出时加大此值', tier: 'styling' },
      xTickAngle: { type: 'number', defaultValue: 0, description: 'X 轴标签旋转角度(deg)，长文本建议 30~45', tier: 'styling' },
      showGrid: { type: 'boolean', defaultValue: true, description: '是否显示网格线', tier: 'styling' },
      referenceValue: { type: 'number', description: '参考线数值，标注 KPI 目标线', tier: 'common' },
      referenceLabel: { type: 'string', description: '参考线标签文字', tier: 'common' },
      referenceColor: { type: 'string', defaultValue: '#ff4d4f', description: '参考线颜色', tier: 'styling' },
      targetValue: { type: 'number', description: '条件着色阈值，高于此值达标绿、低于未达标红', tier: 'common' },
      colorAbove: { type: 'string', defaultValue: '#52c41a', description: '达标（高于阈值）的颜色', tier: 'styling' },
      colorBelow: { type: 'string', defaultValue: '#ff4d4f', description: '未达标（低于阈值）的颜色', tier: 'styling' },
      reactionId: { type: 'string', description: '点击图表元素时触发的 Reaction ID', tier: 'common' },
    },
  },
  RadarChart: {
    type: 'RadarChart',
    description: '雷达图，适合多指标对比和综合评估',
    category: 'chart',
    events: {
      chartClick: {
        description: '点击雷达图数据点时触发',
        mapsTo: 'click',
        payload: '{ reactionId: 绑定的 Reaction ID, clickData: 被点击数据点的数据 }',
      },
    },
    props: {
      data: { type: 'DynamicValue', required: true, description: '图表数据数组的 DataBinding { path }', tier: 'core' },
      nameKey: { type: 'string', required: true, description: '维度名称字段名，如 "metric"', tier: 'core' },
      dataKey: { type: 'string', required: true, description: '数值字段名，如 "score"', tier: 'core' },
      title: { type: 'string', description: '图表标题', tier: 'common' },
      height: { type: 'number', defaultValue: 300, description: '图表高度(px)', tier: 'styling' },
      width: { type: 'string', defaultValue: '100%', description: '图表宽度，如 100% / 500px / 20rem', tier: 'styling' },
      color: { type: 'string', defaultValue: '#1890ff', description: '雷达图颜色', tier: 'styling' },
      fillOpacity: { type: 'number', defaultValue: 0.3, description: '填充透明度(0~1)', tier: 'styling' },
      strokeWidth: { type: 'number', defaultValue: 2, description: '边线粗细(px)', tier: 'styling' },
      showLegend: { type: 'boolean', defaultValue: true, description: '是否显示图例', tier: 'common' },
      showTooltip: { type: 'boolean', defaultValue: true, description: '是否显示悬浮提示', tier: 'common' },
      showDataLabel: { type: 'boolean', defaultValue: false, description: '是否在图表元素上显示数值标签', tier: 'styling' },
      _w: { type: 'number', description: '在 Dashboard 中占列数，默认占满整行', tier: 'styling' },
      fontSize: { type: 'number', defaultValue: 13, description: '全局字号(px)，影响轴刻度/图例/Tooltip/标签', tier: 'styling' },
      fontFamily: { type: 'string', defaultValue: "Inter, system-ui, -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif", description: '字体栈，保证中英文美观渲染', tier: 'styling' },
      chartMargin: { type: 'number', defaultValue: 16, description: '图表四周边距(px)，文字溢出时加大此值', tier: 'styling' },
      reactionId: { type: 'string', description: '点击图表元素时触发的 Reaction ID', tier: 'common' },
    },
  },
  RadialBarChart: {
    type: 'RadialBarChart',
    description: '径向柱状图，适合环形进度/仪表盘展示',
    category: 'chart',
    events: {
      chartClick: {
        description: '点击径向柱状图元素时触发',
        mapsTo: 'click',
        payload: '{ reactionId: 绑定的 Reaction ID, clickData: 被点击元素的数据 }',
      },
    },
    props: {
      data: { type: 'DynamicValue', required: true, description: '图表数据数组的 DataBinding { path }', tier: 'core' },
      nameKey: { type: 'string', required: true, description: '类别名称字段名', tier: 'core' },
      valueKey: { type: 'string', required: true, description: '数值字段名', tier: 'core' },
      title: { type: 'string', description: '图表标题', tier: 'common' },
      height: { type: 'number', defaultValue: 300, description: '图表高度(px)', tier: 'styling' },
      width: { type: 'string', defaultValue: '100%', description: '图表宽度，如 100% / 500px / 20rem', tier: 'styling' },
      colors: { type: 'string', defaultValue: '#1890ff,#52c41a,#faad14,#f5222d,#722ed1', description: '逗号分隔的颜色列表', tier: 'styling' },
      innerRadius: { type: 'number', defaultValue: 30, description: '内径(px)', tier: 'styling' },
      outerRadius: { type: 'number', defaultValue: 120, description: '外径(px)', tier: 'styling' },
      showLegend: { type: 'boolean', defaultValue: true, description: '是否显示图例', tier: 'common' },
      showTooltip: { type: 'boolean', defaultValue: true, description: '是否显示悬浮提示', tier: 'common' },
      showDataLabel: { type: 'boolean', defaultValue: false, description: '是否在图表元素上显示数值标签', tier: 'styling' },
      _w: { type: 'number', description: '在 Dashboard 中占列数，默认占满整行', tier: 'styling' },
      fontSize: { type: 'number', defaultValue: 13, description: '全局字号(px)，影响轴刻度/图例/Tooltip/标签', tier: 'styling' },
      fontFamily: { type: 'string', defaultValue: "Inter, system-ui, -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif", description: '字体栈，保证中英文美观渲染', tier: 'styling' },
      chartMargin: { type: 'number', defaultValue: 16, description: '图表四周边距(px)，文字溢出时加大此值', tier: 'styling' },
      reactionId: { type: 'string', description: '点击图表元素时触发的 Reaction ID', tier: 'common' },
    },
  },
  StatCard: {
    type: 'StatCard',
    description: 'KPI 指标卡，展示核心数字 + 同比趋势箭头 + 迷你趋势线',
    category: 'chart',
    props: {
      label: { type: 'string', required: true, description: '指标名称', tier: 'core' },
      value: { type: 'DynamicValue', required: true, description: '指标数值', tier: 'core' },
      prefix: { type: 'string', description: '数值前缀，如 ¥ / $', tier: 'common' },
      suffix: { type: 'string', description: '数值后缀，如 万元 / %', tier: 'common' },
      trend: { type: 'number', description: '同比变化百分比，正值↑绿色，负值↓红色', tier: 'common' },
      trendLabel: { type: 'string', description: '趋势说明文字，如 "同比" / "较上月"', tier: 'common' },
      sparklineData: { type: 'DynamicValue', description: '迷你趋势线数据，纯数值数组如 [420,380,510,460,590,650]', tier: 'common' },
      sparklineColor: { type: 'string', description: '趋势线颜色，默认跟随 trend 正负自动着色', tier: 'styling' },
      height: { type: 'number', defaultValue: 150, description: '卡片高度(px)', tier: 'styling' },
      width: { type: 'string', defaultValue: '100%', description: '卡片宽度', tier: 'styling' },
      color: { type: 'string', defaultValue: '#1890ff', description: '主题色，用于数值和边框强调', tier: 'styling' },
      _w: { type: 'number', description: '在 Dashboard 中占列数，默认占满整行', tier: 'styling' },
    },
  },
} as const
